name: deeplearning-labs
channels:
  - defaults
  - conda-forge
dependencies:
  - keras=2.9.0
  - jupyter=1.0.0
  - nb_conda=2.2.1
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - spacy[transformers]=3.3.1
  - spacy-transformers=1.1.5
  - pandas=1.4.4
  - numpy=1.22.4
  - pip=22.1.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - wordcloud=1.9.2
  - jedi=0.18.1
  - tensorflow=2.9.1
  - pip:
    - eli5==0.13.0
    - scikit-optimize==0.9.0
    - typing-inspect==0.8.0
    - typing_extensions==4.5.0   
